FROM node:24-alpine

# Values fomr .env file are passed as build arguments
ARG PACKAGE_PATH

WORKDIR /usr/src/app

# Install dependencies
RUN npm install -g nodemon
COPY $PACKAGE_PATH ./
RUN npm install