name: Build and Deploy to Azure Web App for Containers

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # environment: deploydev
    environment: prdjrn

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ vars.AZURE_ACR_NAME }}.azurecr.io

    - name: Build and push Docker image
      run: |
        docker build -f docker/Dockerfile -t ${{ vars.AZURE_ACR_NAME }}.azurecr.io/app:${{ github.sha }} .
        docker push ${{ vars.AZURE_ACR_NAME }}.azurecr.io/app:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        images: ${{ vars.AZURE_ACR_NAME }}.azurecr.io/app:${{ github.sha }}
